"""initial migration

Revision ID: cb89a5ad55b5
Revises: 
Create Date: 2025-03-08 23:48:35.382006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb89a5ad55b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_providers_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.Integer(), nullable=False),
    sa.Column('insee_code', sa.String(length=10), nullable=False),
    sa.Column('type_2g', sa.Boolean(), nullable=False),
    sa.Column('type_3g', sa.Boolean(), nullable=False),
    sa.Column('type_4g', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network_providers_coverage')
    op.drop_table('network_providers')
    # ### end Alembic commands ###
